#!/bin/bash
# build readonly raspberry Pi lite Image FrambOiSe
unset LANG
unset LC_CTYPE
umask 022

echo "# autogenerated from framboise-config" >config
cat framboise-config >>config
touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
./build.sh

